#version 450

layout (binding = 0) uniform ParametersUBO {
    uint width;
    uint height;
} param;

layout (binding = 1, rgba32f) uniform image2D img;

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main() {
    vec3 col = vec3(gl_GlobalInvocationID.x / float(param.width), float(gl_GlobalInvocationID.y) / param.height, 0.0);

    imageStore(img, ivec2(gl_GlobalInvocationID.xy), vec4(col, 1.0));
}
